### ISSUE TITLE
Specifying Configuration

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidify#102]
There are two ways I could go about letting users specify configurations

The first is what I am doing currently. It has the benefit of simplicity, however throws the field wide open for namespace conflicts.

``` yaml
framework: io2012
theme: default
highlighter: highlight.js
hitheme: monokai
```

The alternate approach is to use what `jekyll` and `ruhoh` advocate. It is a little more complicated, but has the advantage of being robust to namespace conflicts. In addition, it allows the use of semantically correct names. For example, I can use `theme` both for the framework as well as the highlighter since they are namespaced.

``` yaml
framework: deck.js
deck.js:
  theme: swiss
  transition: horizontal-slide
highlighter: highlight.js
highlight.js:
  theme: hemisu-light
```
