### ISSUE TITLE
Rethinking Configuration 

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidify#124]
I need to rethink how to handle configuration items such that namespace conflicts are avoided. Here is an example of how I am handling a config item now, and what I think would be a better way to handle it.

**Current Config**

``` yaml
highlighter: prettify
hitheme    : sunburst
```

**Proposed Config**

``` yaml
highlighter: prettify
prettify:
  theme: sunburst
  linenums: true
highlightjs:
  theme: github
```
