### ISSUE TITLE
Allow users to configure markdown processing

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidify#145]
``` yaml
markdown :
  extensions : [no_intra_emphasis, tables, fenced_code,  autolink, 
        strikethrough, lax_spacing,  space_headers, superscript, latex_math]
```
