### ISSUE TITLE
Add logo and subtitle to slides in google io template

### ISSUE THREAD

**Issue by raphg** [ramnathv/slidify#202]
It would be nice to have a YAML option to set a slide wide logo and a subtitle footer on each slide. I manage to do it but I had to hack the CSS file by adding again: 

``` css
slides > slide:not(.nobackground):before {
  font-size: 12pt;
  content: "#yourhashtag";
  position: absolute;
  bottom: 20px;
  left: 60px;
  background: url(../images/google_developers_icon_128.png) no-repeat 0 50%;
  -webkit-background-size: 30px 30px;
  -moz-background-size: 30px 30px;
  -o-background-size: 30px 30px;
  background-size: 30px 30px;
  padding-left: 40px;
  height: 30px;
  line-height: 1.9;
}
```

It looks like you had removed it? It shouldn't be too much work to do it. Your current solution

``` html

---
layout: slide

---
{{{ content }}}
<footer class = 'logo'>
  <img src = './assets/img/logo_BLACK.png'></img>
</footer>
```

Does not work as it simply adds the logo at the top of the slides. Basically footer is not well defined (at least for the google template). 

Hope this makes sense. Good work on the framework, it's nice. Also, the documentation could be improved substantially, but I know that this take time. Thanks!
