### ISSUE TITLE
Make slides completely white (remove box and shadow on box)

### ISSUE THREAD

**Issue by sckott** [ramnathv/slidify#251]
(moved from email exchange)
Since I am not a CSS expert, curious if you can point me in the right direction. 

I can't seem to figure out how to change the color at the bottom of the box-content element in the slides. See the screenshot here http://f.cl.ly/items/432V3A2J3N2F2M1u021d/Screen%20Shot%202013-07-28%20at%208.36.42%20AM.png

I just want the box and the background to be white. 

Response from @ramnathv 

> Add the following two lines to your css. The first line sets the border around the slide to white, while the second line removes the shadow that you see in the screenshot.

``` css
body {background: white};
slides > slide.backdrop{background: white};
```
