### ISSUE TITLE
Allow metadata specification in document using YAML front matter

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidify#39]
I think it would be useful to allow a metadata block in the document where the title, author and date can be specified. I have two options on how to go about it. The main tradeoff is simplicity vs. extensibility. The `pandoc` style title blocks are very simple, but lack the ability to be extended. The `jekyll` or `MMD` style YAML front matter provides a lot of flexibility in the metadata that can be provided.

I think I am going to go with `YAML` front matter, due to the flexibility it offers. I need to think about importing `YAML` or just leaving it as a suggested package. 

**Pandoc Style Title Blocks**

``` pandoc
% title 
% author(s) (separated by semicolons) 
% date
```

**YAML Front Matter**

``` yaml
Title:   A Sample MultiMarkdown Document  
Author:  Fletcher T. Penney  
Date:    February 9, 2011  
Comment: This is a comment intended to demonstrate  
         metadata that spans multiple lines, yet  
         is treated as a single value.  
Test:    And this is a new key-value pair  
```
