### ISSUE TITLE
Folder Structure 

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidify#47]
As `slidify` continues to evolve, here are some additional thoughts on the structure of the assets folder of the slide deck.

``` yml
fonts : font kit downloaded from a source like fontsquirrel
stylesheets : custom css files to include in the slide deck
javascripts  : custom js files to include in slide deck
layouts : layout to use for slide deck
partials: partials to use for slide deck including templates
```
