### ISSUE TITLE
Allow users to specify a configuration file to generate a slide deck.  

### ISSUE THREAD

**Issue by ramnathv** [ramnathv/slidify#7]
Allow users to specify a configuration file to generate a slide deck. 

The idea is similar to `showoff.json` file in `showoff` and `landslide.cfg` in `landslide`. I am thinking of using a `slidify.yml` file to specify the options. Here is how a sample configuration file will look like

``` yaml
source: [intro.Rmd, overview.Rmd, examples]
framework: html5slides
highlighter: R
histyle: acid
```

This should be straightforward to implement now. Here is how I am thinking the logic would work.
1. Check if the slide directory has a `slidify.yml` file.
2. If it does, then set `options = yaml.load_file('slidify.yml')`
3. Else, set `options = slidifyOptions()`

I want to give it a little more thought before implementing this and closing this issue.
